version: '3.8'

services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: demo
    ports:
      - '5434:5432'
#  postgres2:
#    image: postgres:15.4
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 12345
#      POSTGRES_DB: demo
#    ports:
#      - '5434:5432'
